'use strict';
const $=s=>document.querySelector(s),M=MuralModel,T=MuralTagger;
let items=[],tagCatalog=[],view='all',source='all',tag='',activeId=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function db(){return new Promise((resolve,reject)=>{const q=indexedDB.open('mural-mobile',1);q.onupgradeneeded=()=>q.result.createObjectStore('data');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function store(value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('data','readwrite');tx.objectStore('data').put(value,'library');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
async function restore(){const d=await db();return new Promise((resolve,reject)=>{const q=d.transaction('data').objectStore('data').get('library');q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error);});}
function allTags(){return M.cleanCatalog([...tagCatalog,...items.flatMap(i=>i.tags||[])]).sort((a,b)=>a.localeCompare(b,'en'));}
function inView(i){if(i.archived)return false;if(source!=='all'&&(i.source||'x')!==source)return false;if(view==='unread'&&i.read)return false;if(view==='favorites'&&!i.favorite)return false;if(tag&&!i.tags.includes(tag))return false;return true;}
function visible(){const q=$('#search').value.toLocaleLowerCase('pt-BR').trim();return items.filter(i=>inView(i)&&(!q||[i.title,i.subreddit,i.text,i.author,i.handle,i.note,...i.tags].join(' ').toLocaleLowerCase('pt-BR').includes(q))).sort((a,b)=>{const aa=a.date||a.capturedAt,bb=b.date||b.capturedAt;return $('#sort').value==='new'?bb.localeCompare(aa):aa.localeCompare(bb);});}
function render(){
 const has=items.length>0;$('#welcome').hidden=has;$('#library').hidden=!has;$('#bottom').hidden=!has;if(!has)return;
 const sources=[['all','All',items.filter(i=>!i.archived).length],['x','𝕏',items.filter(i=>!i.archived&&(i.source||'x')==='x').length],['reddit','Reddit',items.filter(i=>!i.archived&&i.source==='reddit').length]];
 $('#sources').innerHTML=sources.map(([v,n,c])=>`<button data-source="${v}" class="${source===v?'active':''}">${n} · ${c}</button>`).join('');
 $('#tags').innerHTML=allTags().map(t=>`<button data-tag="${esc(t)}" class="${tag===t?'active':''}">${esc(t)}</button>`).join('');
 const list=visible();$('#count').textContent=`${list.length} ${list.length===1?'achado':'achados'}`;$('#none').hidden=list.length>0;
 $('#grid').innerHTML=list.map(i=>`<button class="card" data-id="${esc(i.id)}">${i.images?.length?`<img src="${esc(i.images[0])}" loading="lazy" referrerpolicy="no-referrer" alt="">`:''}<div class="card-body"><div class="who">${esc(i.author)}</div><div class="where">${esc(i.source==='reddit'?(i.subreddit?'r/'+i.subreddit:'Reddit'):(i.handle?'@'+i.handle:'X'))}</div>${i.title?`<div class="title">${esc(i.title)}</div>`:''}<div class="text">${esc(i.text||'Um achado para revisitar.')}</div><div class="mini-tags">${i.tags.map(t=>`<span class="mini-tag">${esc(t)}</span>`).join('')}</div><div class="meta"><span>${i.type==='image'?'◩ Imagem':i.type==='video'?'▶ Vídeo':'≡ Texto'}</span><span>${i.favorite?'★ ':''}${i.read?'✓ Visto':'○ Explorar'}</span></div></div></button>`).join('');
 document.querySelectorAll('#bottom [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
}
function addTag(input,value){input.value=M.cleanTags([...input.value.split(','),value]).join(', ');}
function openDetail(id){const i=items.find(x=>x.id===id);if(!i)return;activeId=id;const known=allTags().filter(t=>!i.tags.includes(t)),suggestions=T.suggest(i,items);$('#detail-body').innerHTML=`<p class="kicker">${esc(i.source==='reddit'?'REDDIT':'X / TWITTER')}</p><h2>${esc(i.title||i.author)}</h2>${i.images.map(src=>`<img class="detail-image" src="${esc(src)}" referrerpolicy="no-referrer" alt="">`).join('')}<p class="detail-text">${esc(i.text||'Post sem texto capturado.')}</p><label class="field">Tags</label><input id="edit-tags" class="tag-input" value="${esc(i.tags.join(', '))}" placeholder="Nova tag ou várias separadas por vírgula">${known.length?`<select id="picker" class="picker"><option value="">＋ Selecionar tag existente…</option>${known.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}</select>`:''}${suggestions.length?`<div class="suggestions">${suggestions.map(x=>`<button class="suggestion" data-suggest="${esc(x.tag)}">＋ ${esc(x.tag)}</button>`).join('')}</div>`:''}<label class="field">Nota</label><textarea id="edit-note" placeholder="Por que você salvou?">${esc(i.note)}</textarea><div class="checks"><label><input id="edit-fav" type="checkbox" ${i.favorite?'checked':''}> Favorito</label><label><input id="edit-read" type="checkbox" ${i.read?'checked':''}> Já explorei</label></div><button id="save" class="save">Salvar neste iPhone</button><a class="original" href="${esc(i.url)}" target="_blank" rel="noopener">Abrir original ↗</a>`;
 $('#picker')?.addEventListener('change',e=>{if(e.target.value){addTag($('#edit-tags'),e.target.value);e.target.selectedOptions[0]?.remove();e.target.value='';}});
 document.querySelectorAll('[data-suggest]').forEach(b=>b.onclick=()=>{addTag($('#edit-tags'),b.dataset.suggest);b.remove();});
 $('#save').onclick=async()=>{const edited=M.cleanTags($('#edit-tags').value.split(','));items=items.map(x=>x.id!==id?x:{...x,tags:edited,note:$('#edit-note').value,favorite:$('#edit-fav').checked,read:$('#edit-read').checked});tagCatalog=M.cleanCatalog([...tagCatalog,...edited]);await store(M.backup(items,tagCatalog));$('#detail').close();render();toast('Salvo neste iPhone.');};$('#detail').showModal();
}
async function importFile(file){if(!file)return;try{if(file.size>50_000_000)throw Error('O arquivo ultrapassa 50 MB.');const parsed=M.parse(await file.text());if(parsed.backup){items=parsed.items;tagCatalog=parsed.tagCatalog;}else{const merged=M.merge(items,parsed.items);items=merged.items;tagCatalog=M.cleanCatalog([...tagCatalog,...parsed.tagCatalog]);}await store(M.backup(items,tagCatalog));view=source='all';tag='';render();document.querySelectorAll('dialog[open]').forEach(d=>d.close());toast(`${items.length} itens disponíveis neste iPhone.`);}catch(e){toast('Não foi possível importar: '+e.message);}finally{document.querySelectorAll('input[type=file]').forEach(x=>x.value='');}}
async function exportBackup(){const text=JSON.stringify(M.backup(items,tagCatalog),null,2),file=new File([text],`Mural-iPhone-${new Date().toISOString().slice(0,10)}.json`,{type:'application/json'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Backup do Mural'});return;}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){if(e.name!=='AbortError')toast('Não foi possível exportar.');}}
$('#first-import').onchange=e=>importFile(e.target.files[0]);$('#menu-import').onchange=e=>importFile(e.target.files[0]);$('#search').oninput=render;$('#sort').onchange=render;$('#grid').onclick=e=>{const card=e.target.closest('[data-id]');if(card)openDetail(card.dataset.id);};$('#sources').onclick=e=>{const b=e.target.closest('[data-source]');if(b){source=b.dataset.source;render();}};$('#tags').onclick=e=>{const b=e.target.closest('[data-tag]');if(b){tag=tag===b.dataset.tag?'':b.dataset.tag;render();}};$('#bottom').onclick=e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;tag='';render();scrollTo({top:0,behavior:'smooth'});}};$('#bottom-tags').onclick=()=>{scrollTo({top:210,behavior:'smooth'});};$('#more').onclick=()=>$('#menu').showModal();$('#export').onclick=exportBackup;$('#install').onclick=$('#show-install').onclick=()=>{$('#menu').close();$('#install-help').showModal();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
(async()=>{try{const saved=await restore();if(saved){const parsed=M.parse(saved);items=parsed.items;tagCatalog=parsed.tagCatalog;}}catch(e){toast('Não foi possível abrir o armazenamento local.');}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=3').catch(()=>{});})();
